/**
 * Test Vision Point Poster Generation System
 * Tests poster creation from existing scripts with different styles
 */

const path = require('path');
const fs = require('fs-extra');
const {
  generatePosterFromScript,
  generatePostersForAllScripts,
  generatePosterContentAI,
  extractPosterContent
} = require('./vision_point_poster_generator');

// Test configuration
const SCRIPTS_DIR = path.join(__dirname, 'generated_scripts');
const OUTPUT_DIR = path.join(__dirname, 'output', 'posters');

/**
 * Test single poster generation
 */
async function testSinglePosterGeneration() {
  console.log('🧪 Testing Single Poster Generation');
  console.log('=' .repeat(50));
  
  try {
    // Find a sample script
    const scriptFiles = await fs.readdir(SCRIPTS_DIR);
    const urduScripts = scriptFiles.filter(file => 
      file.includes('urdu') && file.endsWith('.txt')
    );
    
    if (urduScripts.length === 0) {
      console.log('❌ No Urdu scripts found for testing');
      return false;
    }
    
    const testScript = urduScripts[0];
    const scriptPath = path.join(SCRIPTS_DIR, testScript);
    
    console.log(`📄 Testing with script: ${testScript}`);
    
    // Test different poster styles
    const styles = ['news', 'breaking', 'analysis', 'feature'];
    
    for (const style of styles) {
      console.log(`\n🎨 Testing ${style} style poster...`);
      
      const result = await generatePosterFromScript(scriptPath, {
        style: style,
        generateBackground: true
      });
      
      if (result.success) {
        console.log(`✅ ${style} poster generated successfully!`);
        console.log(`📁 File: ${result.filename}`);
      } else {
        console.log(`❌ ${style} poster failed: ${result.error}`);
      }
    }
    
    return true;
    
  } catch (error) {
    console.error(`❌ Single poster test failed: ${error.message}`);
    return false;
  }
}

/**
 * Test content extraction
 */
async function testContentExtraction() {
  console.log('\n🧪 Testing Content Extraction');
  console.log('=' .repeat(50));
  
  try {
    // Sample Urdu script content
    const sampleUrduScript = `
پاکستان میں ڈیجیٹل میڈیا کا کردار

آج کے دور میں ڈیجیٹل میڈیا نے پاکستان میں انقلاب برپا کر دیا ہے۔ سوشل میڈیا پلیٹفارمز کے ذریعے لوگ اپنی آواز بلند کر رہے ہیں۔

اہم نکات:
- یوٹیوب اور فیس بک کا بڑھتا ہوا استعمال
- نوجوانوں میں ڈیجیٹل کنٹنٹ کی مقبولیت  
- روایتی میڈیا کو نئے چیلنجز

[VISUAL CUE: Pakistani youth using smartphones and social media]

یہ تبدیلی نہ صرف معلومات کے حصول میں آسانی لائی ہے بلکہ کاروباری مواقع بھی فراہم کیے ہیں۔

Generated by Vision Point Content Team
    `;
    
    console.log('📝 Testing content extraction...');
    const extracted = extractPosterContent(sampleUrduScript);
    
    console.log('✅ Content extraction results:');
    console.log(`📌 Main Topic: ${extracted.mainTopic}`);
    console.log(`🔢 Word Count: ${extracted.wordCount}`);
    console.log(`🌐 Language: ${extracted.language}`);
    console.log(`📋 Key Points: ${extracted.keyPoints.length}`);
    
    extracted.keyPoints.forEach((point, index) => {
      console.log(`   ${index + 1}. ${point}`);
    });
    
    return true;
    
  } catch (error) {
    console.error(`❌ Content extraction test failed: ${error.message}`);
    return false;
  }
}

/**
 * Test AI poster content generation
 */
async function testAIPosterGeneration() {
  console.log('\n🧪 Testing AI Poster Content Generation');
  console.log('=' .repeat(50));
  
  try {
    const sampleScript = `
پاکستان میں تعلیمی بحران

پاکستان میں تعلیمی نظام کو بہتر بنانے کی ضرورت ہے۔ حکومت نے نئی پالیسیاں متعارف کرائی ہیں۔

- سکولوں میں جدید ٹیکنالوجی کا استعمال
- اساتذہ کی تربیت میں بہتری
- دیہی علاقوں میں تعلیمی سہولات

یہ اقدامات مستقبل میں بہتر نتائج لا سکتے ہیں۔
    `;
    
    console.log('🤖 Testing AI poster content generation...');
    
    const posterContent = await generatePosterContentAI(sampleScript, 'news');
    
    console.log('✅ AI poster content generated:');
    console.log(`📌 Title: ${posterContent.title}`);
    console.log(`📝 Subtitle: ${posterContent.subtitle}`);
    console.log(`🎯 CTA: ${posterContent.callToAction}`);
    console.log(`#️⃣ Hashtags: ${posterContent.hashtags}`);
    
    return true;
    
  } catch (error) {
    console.error(`❌ AI poster generation test failed: ${error.message}`);
    return false;
  }
}

/**
 * Test batch poster generation
 */
async function testBatchPosterGeneration() {
  console.log('\n🧪 Testing Batch Poster Generation');
  console.log('=' .repeat(50));
  
  try {
    console.log('📁 Generating posters for first 3 scripts...');
    
    // Get first 3 scripts for testing
    const scriptFiles = await fs.readdir(SCRIPTS_DIR);
    const testScripts = scriptFiles
      .filter(file => file.endsWith('.txt'))
      .slice(0, 3);
    
    if (testScripts.length === 0) {
      console.log('❌ No scripts found for batch testing');
      return false;
    }
    
    console.log(`📋 Testing with ${testScripts.length} scripts:`);
    testScripts.forEach((script, index) => {
      console.log(`   ${index + 1}. ${script}`);
    });
    
    // Create temporary directory with test scripts
    const tempDir = path.join(__dirname, 'temp_test_scripts');
    await fs.ensureDir(tempDir);
    
    // Copy test scripts
    for (const script of testScripts) {
      const sourcePath = path.join(SCRIPTS_DIR, script);
      const destPath = path.join(tempDir, script);
      await fs.copy(sourcePath, destPath);
    }
    
    // Generate posters
    const results = await generatePostersForAllScripts(tempDir, {
      style: 'news',
      generateBackground: false // Skip background generation for faster testing
    });
    
    // Clean up temp directory
    await fs.remove(tempDir);
    
    const successCount = results.filter(r => r.success).length;
    console.log(`✅ Batch generation completed: ${successCount}/${results.length} successful`);
    
    return successCount > 0;
    
  } catch (error) {
    console.error(`❌ Batch poster generation test failed: ${error.message}`);
    return false;
  }
}

/**
 * Test output directory and file structure
 */
async function testOutputStructure() {
  console.log('\n🧪 Testing Output Structure');
  console.log('=' .repeat(50));
  
  try {
    // Ensure output directory exists
    await fs.ensureDir(OUTPUT_DIR);
    
    // Check if directory is writable
    const testFile = path.join(OUTPUT_DIR, 'test_write.txt');
    await fs.writeFile(testFile, 'test');
    await fs.remove(testFile);
    
    console.log('✅ Output directory is accessible and writable');
    console.log(`📂 Output path: ${OUTPUT_DIR}`);
    
    // List existing posters
    const existingFiles = await fs.readdir(OUTPUT_DIR).catch(() => []);
    console.log(`📄 Existing poster files: ${existingFiles.length}`);
    
    return true;
    
  } catch (error) {
    console.error(`❌ Output structure test failed: ${error.message}`);
    return false;
  }
}

/**
 * Run comprehensive poster generation tests
 */
async function runComprehensiveTests() {
  console.log('🎨 VISION POINT POSTER GENERATION TESTS');
  console.log('=' .repeat(60));
  console.log('Testing comprehensive poster generation system...\n');
  
  const tests = [
    { name: 'Output Structure', fn: testOutputStructure },
    { name: 'Content Extraction', fn: testContentExtraction },
    { name: 'AI Poster Generation', fn: testAIPosterGeneration },
    { name: 'Single Poster Generation', fn: testSinglePosterGeneration },
    { name: 'Batch Poster Generation', fn: testBatchPosterGeneration }
  ];
  
  const results = [];
  
  for (const test of tests) {
    try {
      console.log(`\n🧪 Running ${test.name} test...`);
      const result = await test.fn();
      results.push({ name: test.name, success: result });
      
      if (result) {
        console.log(`✅ ${test.name} test PASSED`);
      } else {
        console.log(`❌ ${test.name} test FAILED`);
      }
    } catch (error) {
      console.error(`❌ ${test.name} test ERROR: ${error.message}`);
      results.push({ name: test.name, success: false, error: error.message });
    }
  }
  
  // Final summary
  const passedTests = results.filter(r => r.success).length;
  const totalTests = results.length;
  
  console.log('\n' + '='.repeat(60));
  console.log('🎉 VISION POINT POSTER TESTS SUMMARY');
  console.log('='.repeat(60));
  console.log(`✅ Passed: ${passedTests}/${totalTests} tests`);
  console.log(`❌ Failed: ${totalTests - passedTests}/${totalTests} tests`);
  
  if (passedTests === totalTests) {
    console.log('\n🎊 ALL TESTS PASSED! Vision Point poster system is ready!');
    console.log('📂 Check ./output/posters/ for generated posters');
  } else {
    console.log('\n⚠️ Some tests failed. Please check the errors above.');
  }
  
  // Save test results
  const reportPath = path.join(__dirname, `poster_test_results_${Date.now()}.json`);
  await fs.writeFile(reportPath, JSON.stringify({
    timestamp: new Date().toISOString(),
    totalTests,
    passedTests,
    results
  }, null, 2));
  
  console.log(`📊 Test report saved: ${path.basename(reportPath)}`);
  
  return passedTests === totalTests;
}

// Run tests if called directly
if (require.main === module) {
  runComprehensiveTests()
    .then(success => {
      process.exit(success ? 0 : 1);
    })
    .catch(error => {
      console.error('❌ Test execution failed:', error);
      process.exit(1);
    });
}

module.exports = {
  runComprehensiveTests,
  testSinglePosterGeneration,
  testBatchPosterGeneration,
  testContentExtraction,
  testAIPosterGeneration
};